# fly.toml app configuration file generated for fiction-logs on 2024-04-17T10:18:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fiction-logs'
primary_region = 'lax'

[build]
image = 'flyio/log-shipper:latest'

[http_service]
internal_port = 8686
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = [ 'app' ]

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
