packages:
  - '@fiction/core'
  - '@fiction/ui'
  - '@fiction/www'
  - '@fiction/site'
  - '@fiction/admin'
  - '@fiction/cards'
  - '@fiction/analytics'
  - '@fiction/platform'
  - '@fiction/posts'
  - '@fiction/forms'
  - '@fiction/themes/*'
  - '@fiction/plugins/*'
