# To connect from SSL, requires: jdbc:clickhouse://<HOST>:8123/?ssl=true&sslmode=STRICT
# jdbc:clickhouse://fiction-clickhouse.fly.dev:8123
# DBeaver Insructions: https://clickhouse.com/docs/en/integrations/dbeaver
# https://github.com/ClickHouse/clickhouse-jdbc/issues/847

app = "fiction-clickhouse"

[build]
image = "clickhouse/clickhouse-server@latest"

[env]
CLICKHOUSE_DATABASE = "fiction"
CLICKHOUSE_USER = "fiction"
CLICKHOUSE_PASSWORD = "socrates-and-plato"

[mounts]
source = "clickhouse_data"
destination = "/var/lib/clickhouse/"

[[services]]
internal_port = 8123
protocol = "tcp"

[services.concurrency]
hard_limit = 50
soft_limit = 30

[[services.ports]]
handlers = [
  "tls",
  "http"
]
port = 8123

[[services.ports]]
handlers = [
  "tls",
  "http"
]
port = 443

[[services.tcp_checks]]
interval = 10000
timeout = 2000

[[services]]
internal_port = 9000
protocol = "tcp"

[[services.ports]]
handlers = [ "tls" ]
port = 9000

[[services.tcp_checks]]
interval = 10000
timeout = 2000

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
