app = "fiction-sites"
primary_region = "lax"

[build]
dockerfile = "./Dockerfile"
build-target = "fiction-sites"

[http_service]
internal_port = 6565
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = [ 'app' ]

[[http_service.checks]]
port = 6565
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "8s"
path = "/"
tls_skip_verify = false

[deploy]
strategy = "bluegreen"

[[vm]]
size = "shared-cpu-2x"
memory = "4gb"
