app = "fiction-website"
primary_region = "lax"

[build]
dockerfile = "./Dockerfile"
build-target = "fiction-www"

[http_service]
internal_port = 4444
processes = [ 'app' ]
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
[http_service.concurrency]
  type = "requests"
  soft_limit = 200
  hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"
tls_skip_verify = false

[deploy]
strategy = "bluegreen"

[[vm]]
size = "shared-cpu-2x"
memory = "4gb"
